# 上下班配置 下班的群聊列表 配置后该群将无法触发任何功能
noWork:
  - "636023444"

# 抽幸运字符成功后是否渲染图片
word_render: true

# 谁艾特我(注: 开启时，群多可能会对性能产生影响)
whoat: false

# 消息前缀
msg_prefix: ""

# 消息后缀
msg_suffix: ""

#联系主人
contactMaster:
  # 是否启用
  enable: true
  # 为true时，是否只发送第一个主人
  allow: false
  # cd
  cd: 60
